#!/bin/bash

# SCRIPT PARA OBTENER TOKEN PERMANENTE DE FACEBOOK

echo "🔧 SOLUCIÓN RÁPIDA PARA FACEBOOK TOKEN"
echo "======================================"
echo ""
echo "📋 PASOS PARA SOLUCIONAR:"
echo ""
echo "1. Ve a n8n: https://vmi2907616.contaboserver.net"
echo "2. Busca la credencial 'FB TOKEN'"
echo "3. Haz clic en 'Connect my account' (reautorizar)"
echo "4. Acepta TODOS los permisos de Facebook"
echo "5. IMPORTANTE: Cuando pregunte por páginas, selecciona tu página"
echo "6. Copia el nuevo token desde n8n"
echo "7. Ejecuta este comando con tu nuevo token:"
echo ""
echo "   export FACEBOOK_ACCESS_TOKEN='TU_NUEVO_TOKEN_AQUI'"
echo "   echo 'FACEBOOK_ACCESS_TOKEN=\"TU_NUEVO_TOKEN_AQUI\"' >> .env"
echo ""
echo "🎯 VERIFICACIÓN:"
echo "   curl 'http://localhost:3000/api/facebook-token-info?useConfig=true'"
echo ""
echo "✅ Deberías ver:"
echo "   - tokenType: 'PAGE' (no 'USER')"
echo "   - isValid: true"
echo "   - expiresAt: 0 o null (permanente)"
echo ""
echo "🚀 Una vez hecho esto, las publicaciones funcionarán!"