#!/bin/bash

echo "🚀 Configuración de GitHub Secrets para Auto-Deploy"
echo "=================================================="
echo ""
echo "Ve a tu repositorio de GitHub:"
echo "https://github.com/desings/dashboard-marketing/settings/secrets/actions"
echo ""
echo "Y agrega estos secrets:"
echo ""
echo "1. VERCEL_TOKEN:"
echo "   - Ve a https://vercel.com/account/tokens"
echo "   - Crea un nuevo token"
echo "   - Cópialo y pégalo en GitHub"
echo ""
echo "2. VERCEL_ORG_ID: team_RwHPZPAWO6GzsOYI4scddopY"
echo ""
echo "3. VERCEL_PROJECT_ID: prj_IB8LFgWy9fZ2kYdRlxczb5LdlsWf"
echo ""
echo "4. SUPABASE_URL: https://rgmltuyfabxomkplvzij.supabase.co"
echo ""
echo "5. SUPABASE_ANON_KEY:"
echo "   - Ve a tu proyecto Supabase > Settings > API"
echo "   - Copia la 'anon/public' key"
echo ""
echo "6. FACEBOOK_APP_ID: 1314977153875955"
echo ""
echo "7. FACEBOOK_APP_SECRET: a797d865b513dc152ed306d420ee581c"
echo ""
echo "8. NEXTAUTH_SECRET: development-nextauth-secret"
echo ""
echo "9. NEXTAUTH_URL: https://dashboard-marketing-a62m.vercel.app"
echo ""
echo "Una vez agregues todos los secrets, haz push y el deploy será automático ✅"